language: python
python:
  - 2.7

sudo: required
dist: trusty

env:
  #- ANSIBLE_VERSION=1.9.4
  - ANSIBLE_VERSION=2.4.2.0
  - ANSIBLE_VERSION=2.4.1.0
  
before_install:
  - sudo apt-get install -y python-dev libxml2-dev python-pip libxslt1-dev build-essential libssl-dev libffi-dev

install:
  - pip install -r requirements.txt
  - pip install -q ansible==$ANSIBLE_VERSION
  - ansible-galaxy --force install Juniper.junos,1.4.3 -p ./

script:
  - ansible-playbook assemble/pb.yml
  - ansible-playbook junos_jsnapy/pb_test_file_snap_snap_check.yml --syntax-check
  - ansible-playbook junos_ping/pb.yml --syntax-check
  - ansible-playbook junos_install_conf/pb_bgp_replace.yml --syntax-check
  - ansible-playbook junos_command/pb_check_op_states.yml --syntax-check

branches:
  only:
   - master

notifications:
  email:
    recipients:
      - khelil.sator.git@gmail.com
    on_failure: always
  slack: 
    ksator-junos:XAUJP6A29mgYtUtGIJQdPBS7


